### ISSUE TITLE
Add Make?

### ISSUE THREAD

**Issue by lukejackson96** [TomChate/ComPChecker#3]
What is this 'Add Make' form? 

Add make as in brand of component? A make as in a build? The form isn't very detailed and the java file is not commented so it's hard to tell what this is.

**Comment by TomChate** [comment]
Make is something like Acer/Intel.

**Comment by lukejackson96** [comment]
What is the use of the 'Add Make' form then? Are component brands not going to be saved as SQL columns/data entries in our database? Are we going to be doing searching and sorting via the database? If so, what is the point of this 'Add Make' form?
