### ISSUE TITLE
Fonts etc?

### ISSUE THREAD

**Issue by lukejackson96** [TomChate/ComPChecker#4]
In our design documentation we didn't go into detail about the details of our UI. For example fonts, colours, and heading sizes. Have we got any we've decided on and rationale behind that so we can be designing and updating our forms to be consistent?

**Comment by TomChate** [comment]
I think at the moment we need to focus on logical function over GUI. We can go back and change the GUI once we know it works.

**Comment by lukejackson96** [comment]
True I agree, I just thought if anyone had any suggestions it would be best to suggest now for ongoing consistency, rather than giving ourselves extra work having to go back changing things.

**Comment by TomChate** [comment]
I think it's best we give that task to someone with experience.

**Comment by lukejackson96** [comment]
Fair enough I simply thought I would bring it up while I was sorting out some forms quickly.

**Comment by TomChate** [comment]
Good idea; maybe at the next meeting we can discuss? I think Pawel or Greg would be a good choice?

**Comment by lukejackson96** [comment]
Sure that sounds good.
